### ISSUE TITLE
About devdependencies

### ISSUE THREAD

**Issue by JIBIN-P** [feross/feross-card#4]
Hi, I was trying to implement this project but I faced an error on the command prompt saying no dependencies found for chalk, after which I moved chalked and boxen to dependencies in package.json.

I am using  github actions for publish. How did you manage to put it in devdependencies and make it work after publish, am I missing something.

Sorry I know this is not an issue just a question from my side which I seek your guidance.

Thank you Ferros.

**Comment by feross** [comment]
I'm not sure what GitHub Actions is doing since I've never used it before. I'm sorry I can't help you.
